server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://118.31.55.121:3306/artsystem?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: GlassBottle*.
  #  rabbitmq:
  #    host: 172.16.65.213
  #    port: 5672
  #    username: ems
  #    password: 123
  #    virtual-host: /ems
  redis:
    database: 0
    host: 118.31.55.121
    port: 6379

mybatis:
  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pro:
  scheduler:
    update:
      cron: 0 49 11 * * *
